export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAİLS_REQUEST='PRODUCT_DETAİLS_REQUEST';
export const PRODUCT_DETAİLS_SUCCESS='PRODUCT_DETAİLS_SUCCESS';
export const PRODUCT_DETAİLS_FAIL='PRODUCT_DETAİLS_FAIL';